services:

  backend:
    build: ./backend-spring-boot
    container_name: telinha-backend
    ports:
      - "8088:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=telinhaquente
      - OMDB_API_KEY=4f901358
    networks:
      - telinha-net

  frontend:
    build: ./frontend-react
    container_name: telinha-frontend
    ports:
      - "5173:80"
    networks:
      - telinha-net
    depends_on:
      - backend

networks:
  telinha-net:
    driver: bridge
