
services:

  backend:
    build: ./backend-spring-boot
    container_name: telinha-backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - telinha-net

  frontend:
    build: ./frontend-react
    container_name: telinha-frontend
    ports:
      - "5173:80"
    networks:
      - telinha-net
    depends_on:
      - backend

networks:
  telinha-net:
    driver: bridge
