version: '3.8'

services:

  backend:
    build: ./backend-spring-boot
    container_name: telinha-backend
    ports:
      - "8080:8080"
    networks:
      - telinha-net

  frontend:
    build: ./frontend-react
    container_name: telinha-frontend
    ports:
      - "3000:80"
    networks:
      - telinha-net
    depends_on:
      - backend

networks:
  telinha-net:
    driver: bridge
